### ISSUE TITLE
[TASK] Votable plugin should not be a hard dependency

### ISSUE THREAD

**Issue by lorenzulrich** [visol/ext-votable#18]
Currently, if I want to display the list of candidates without having them votable (e.g. to list all elected candidates), I get an error because the jQuery function votable was not found.

Votable should not be a hard dependency - when the Votable plugin is not present, the candidates should just not be votable.

**Comment by fabarea** [comment]
Fixed via https://github.com/visol/ext-easyvote_smartvote/issues/7
