### ISSUE TITLE
[TASK] Pass cached rank and cached votes data to frontend

### ISSUE THREAD

**Issue by lorenzulrich** [visol/ext-votable#21]
If we deliver the cached rank and cached votes data along the data that is displayed (e.g. Candidates), they would be invalidated each time a user casts a vote. The cache wouldn't make much sense.

EXT:votable should deliver the information of rank and count for each record it is applied to. The information could then be added by JS.

Is this a way to go?

**Comment by fabarea** [comment]
We can do that per javascript and kind of merge the "rank" information into the cached data of candidates to prevent cache invalidation. I am still hesitant whether this info should be generated by EXT:votable or it is so specific to EXT:easyvote_smartvote that it could be implemented in this latter.

**Comment by fabarea** [comment]
Will be solved via https://github.com/visol/ext-easyvote_smartvote/issues/16
